#!/bin/bash

# Check for debug
[[ "$1 $2 $3 $4 $5 $6" =~ (^|[[:space:]])"--debug"($|[[:space:]]) ]] && debug=1
[[ $debug ]] && echo "$1 $2 $3 $4 $5 $6"

# Globals
scriptName="$0"
self="$(pwd)/$scriptName"
linkPath="/usr/bin"

# Help and initial checks
[[ ! $1 ]] && \
echo -e "\e[93mNo argument given.
Use -h for help." && \
exit # if no arguments were given
[[ $1 == -h ]] && \
echo -e " Usage: MakeExec -i <script file>  ||  MakeExec -s  ||  MakeExec -i <script file> -l <link path>
  -i      Input file to make executable
  -s      Make self executable  (optional)
  -l      Change symLink path (optional);
          default is /usr/bin" && \
exit # if only returning help
[[ ! "$EUID" -eq 0 ]] && \
echo -e "\e[93mWarning: Insufficient Permissions. Try sudo." && \
exit # if sudo not given
[[ $1 == -l ]] && \
echo -e "\e[93mWarning: This option can only be used with -i." && \
exit # if -l in wrong position

##  __Main__  ##
if [[ "$1" -eq  "-s" ]] && [[ ! -f "/usr/bin/MakeExec" ]]
then
  linkPath="/usr/bin"
  cp "$self" "$linkPath"
  chmod +x "$linkPath/$scriptName"
  echo -e "\e[96mMakeExec is now available from anywhere"
  exit
elif [[ $1 == -s ]] && [[ -f /usr/bin/MakeExec ]]
then
  echo -e "\e[93mWarning: MakeExec is already available"
  exit
fi

if [[ "$1" -eq "-i" ]] && [[ ! -f /usr/bin/$2 ]] && [[ -f "$(pwd)/$2" ]]
then
  [[ ! $2 ]] && echo -e "\e[31mError: Invalid input file." && exit
  [[ ! -f "$(pwd)/$2" ]] && echo -e "\e[31mError: Invalid input file." && exit
  shebang=$(head $2 -c3)
  [[ "$shebang" != '#!/' ]] && echo -e "\e[93mWarning: No shebang on input file."
  [[ -f "$linkPath/$2" ]] && echo -e "\e[93mWarning:$2 is already available" && exit
  file_to_exec=$2
  fullPath="$(pwd)/$file_to_exec"
  chmod +x "$linkPath/$file_to_exec"
  ln --symbolic  "$fullPath" "$linkPath"
  echo -e "\e[96m$file_to_exec is now available from anywhere"
  exit
elif [[ $1 == -i ]] && [[ ! $2 ]]
then
  echo -e "\e[31mError: No input file given"
  exit
fi
  exit